name: Comment Inactive

on:
  issues:
    types: [labeled]

jobs:
  create-comment:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'inactive'
    steps:
      - name: Create comment
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            Hey @${{ github.event.issue.user.login }}. This issue hasn't had any activity for a while so we're adding the `inactive` tag. If it stays inactive for a few days it'll be closed automatically.
